#!/usr/bin/env python3
"""
Deposit MARCO-BOLO Deliverable D5.5 to Zenodo.

Cover author = Matthias Obst only; V0.6 history row includes Carlota Muñiz.
Per Stephen's pick, both are listed as creators.

Note: D5.5 abstract explicitly attributes the work to "task T5.4" rather than
T5.5 — flagged for PM feedback. Cover date 30.06.2025; Ares ref 05.09.2025.
"""
import argparse, json, os, ssl, sys
import urllib.request, urllib.error
from pathlib import Path

METADATA = {
    "title": "Scientific document summarising the results of the Species distribution modelling and mapping of the alien species impacts on the European coastal and marine habitats",
    "upload_type": "publication",
    "publication_type": "deliverable",
    "publication_date": "2025-09-05",   # Ares date
    "version": "1.0",
    "language": "eng",
    "access_right": "open",
    "license": "cc-by-4.0",
    "creators": [
        {"name": "Obst, Matthias",
         "affiliation": "University of Gothenburg",
         "orcid": "0000-0003-0264-9631"},
        {"name": "Muñiz, Carlota",
         "affiliation": "Flanders Marine Institute",
         "orcid": "0000-0001-9584-3833"},
    ],
    "description": (
        "<p>Grant Agreement: 101082021<br>"
        "Project Acronym: MARCO-BOLO<br>"
        "Project Title: MARine COastal BiOdiversity Long-term Observations<br>"
        "Deliverable Number: D5.5<br>"
        "Work Package Number: WP5<br>"
        "Deliverable Title: Scientific document summarising the results of the Species "
        "distribution modelling and mapping of the alien species impacts on the European "
        "coastal and marine habitats<br>"
        "Due Date: 30.05.2025<br>"
        "Date of delivery (cover): 30.06.2025<br>"
        "Submission (Ares ref): 05.09.2025</p>"

        "<p>This deliverable summarizes the scientific outputs generated by "
        "<strong>Task T5.4</strong> &mdash; &ldquo;Mapping the impacts of Non-Indigenous "
        "species (NIS) on European coastal and marine habitats, based on multi-disciplinary "
        "approaches&rdquo;. In this task we modelled 82 species identified by marine genetic "
        "monitoring programs in 2020&ndash;2024 as occurring outside their native range. "
        "Models produced predictions of suitable habitat in current and future climate "
        "scenarios for these non-indigenous species (NIS) and can be used to identify regions "
        "with elevated risk for establishment and spread of alien species.</p>"

        "<p>The modelling builds on the Species Distribution Model (SDM) workflow developed "
        "for invasive alien species hotspot mapping by the University of Gothenburg, applied "
        "here to species detected by the ARMS-MBON and Swedish national port monitoring "
        "programmes. The models are based on a Random Forest machine learning algorithm using "
        "environmental data layers from Bio-Oracle (Aqua-MODIS and SeaWiFS satellite "
        "products, plus World Ocean Database in situ measurements) for current and future "
        "climate scenarios (SSP119). The model's source code, inputs and results are "
        "available on GitHub at "
        "https://github.com/biomobst/IAS_hotspot_model/tree/master/Modelling_trial_2025.</p>"

        "<p>The genetic monitoring programs that donated the alien species lists for this "
        "experiment do not yet provide enough species occurrence data to influence the "
        "outcome of the model predictions, which means that GBIF and OBIS still provide most "
        "of the occurrence data for the modelling. However, the genetic monitoring programs "
        "do provide the list of species detected to be &ldquo;on the move&rdquo;. For these "
        "species, the models provide valuable knowledge on potential alien species impact as "
        "they are able to align the presently known distribution with the potential "
        "distribution of these species in the future. The SDM analysis tool will be added to "
        "the EDITO platform (Digital Twin of the Ocean) during 2026.</p>"
    ),
    "keywords": [
        "MBO WP5", "alien species", "non-indigenous species",
        "species distribution modelling", "climate projections",
    ],
    "communities": [{"identifier": "marco-bolo"}],
    "grants": [{"id": "10.13039/501100000780::101082021"}],
    "related_identifiers": [],   # D5.5 abstract doesn't explicitly cite D5.4
    "dates": [
        {"start": "2025-06-30", "type": "Created",
         "description": "Date on cover"},
        {"start": "2025-09-05", "type": "Submitted",
         "description": "Submission date (Ares ref)"},
        {"start": "2025-05-30", "type": "Other",
         "description": "Due date"},
    ],
}

# ---------------------------------------------------------------------------
# HTTP plumbing
# ---------------------------------------------------------------------------
def make_ssl_context():
    try:
        import certifi
        return ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        return ssl.create_default_context()

def load_token():
    tok = os.environ.get("ZENODO_TOKEN")
    if tok: return tok.strip()
    tok_file = Path.home() / ".zenodo_token"
    if tok_file.exists():
        return tok_file.read_text().strip()
    print("ERROR: no Zenodo token.", file=sys.stderr); sys.exit(1)

def request(method, url, token, ctx, json_body=None, raw_body=None,
            content_type=None):
    headers = {"Authorization": f"Bearer {token}"}
    if json_body is not None:
        data = json.dumps(json_body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    elif raw_body is not None:
        data = raw_body
        if content_type: headers["Content-Type"] = content_type
    else:
        data = None
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=120, context=ctx) as r:
            body = r.read().decode("utf-8") if r.length != 0 else ""
            return r.status, json.loads(body) if body else {}
    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8", errors="replace")
        print(f"\nHTTP {e.code} {e.reason} on {method} {url}", file=sys.stderr)
        print(f"Response body:\n{err_body}", file=sys.stderr)
        sys.exit(2)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pdf", required=True)
    ap.add_argument("--draft", action="store_true")
    ap.add_argument("--yes", action="store_true")
    args = ap.parse_args()

    pdf = Path(args.pdf).expanduser().resolve()
    if not pdf.is_file():
        print(f"ERROR: file not found: {pdf}", file=sys.stderr); sys.exit(1)

    token = load_token()
    ctx = make_ssl_context()
    base = "https://zenodo.org"
    print(f"Target: LIVE ({base})")
    print(f"File:   {pdf}  ({pdf.stat().st_size:,} bytes)")
    print(f"Title:  {METADATA['title'][:80]}...")
    print(f"Authors: {len(METADATA['creators'])}\n")

    print("Step 1/4: creating draft deposit ...")
    status, dep = request("POST", f"{base}/api/deposit/depositions", token, ctx,
                          json_body={})
    deposit_id = dep["id"]
    bucket_url = dep["links"]["bucket"]
    html_url = dep["links"].get("html") or f"{base}/deposit/{deposit_id}"
    print(f"  deposit id: {deposit_id}\n  review URL: {html_url}")

    print(f"\nStep 2/4: uploading {pdf.name} ...")
    with open(pdf, "rb") as fh: body = fh.read()
    status, fileinfo = request("PUT", f"{bucket_url}/{pdf.name}", token, ctx,
                               raw_body=body,
                               content_type="application/octet-stream")
    print(f"  uploaded ({fileinfo.get('size','?')} bytes)")

    print("\nStep 3/4: setting metadata ...")
    status, dep = request("PUT", f"{base}/api/deposit/depositions/{deposit_id}",
                          token, ctx, json_body={"metadata": METADATA})
    print(f"  metadata saved. Reserved DOI: "
          f"{dep['metadata'].get('prereserve_doi',{}).get('doi','(unknown)')}")

    if args.draft:
        print(f"\nStep 4/4: SKIPPED (--draft). Review/publish at:\n  {html_url}")
        return
    if not args.yes:
        print(f"\nReview the draft here before publishing:\n  {html_url}")
        ans = input("\nPublish now to LIVE? Permanent DOI. [y/N]: ")
        if ans.strip().lower() not in ("y", "yes"):
            print(f"Not publishing. Draft saved at:\n  {html_url}")
            return

    print("\nStep 4/4: publishing ...")
    status, dep = request(
        "POST", f"{base}/api/deposit/depositions/{deposit_id}/actions/publish",
        token, ctx)
    final_doi = dep.get("doi") or dep["metadata"].get("doi")
    final_url = dep["links"].get("record_html") or dep["links"].get("html")
    print("\n✓ Published.")
    print(f"  DOI:    {final_doi}")
    print(f"  URL:    {final_url}")

if __name__ == "__main__":
    main()
