#!/usr/bin/env python3
"""
Deposit MARCO-BOLO Deliverable D5.4 to Zenodo.

Cover date 30.05.2024; Submission Date 30.05.2024 (on time); Ares ref 25/06/2024.
Per convention: publication_date = Ares date (formal EU submission).
"""
import argparse, json, os, ssl, sys
import urllib.request, urllib.error
from pathlib import Path

METADATA = {
    "title": "Summary of results on the multi-disciplinary mapping of the alien species distribution and impacts on the European coastal and marine habitats",
    "upload_type": "publication",
    "publication_type": "deliverable",
    "publication_date": "2024-06-25",   # Ares date
    "version": "1.0",
    "language": "eng",
    "access_right": "open",
    "license": "cc-by-4.0",
    "creators": [
        {"name": "Obst, Matthias",
         "affiliation": "University of Gothenburg",
         "orcid": "0000-0003-0264-9631"},
        {"name": "Daraghmeh, Nauras",
         "affiliation": "University of Gothenburg",
         "orcid": "0000-0001-8261-824X"},
        {"name": "Pagnier, Justine",
         "affiliation": "University of Gothenburg; Lifewatch ERIC"},
        {"name": "Exter, Katrina",
         "affiliation": "Flanders Marine Institute (VLIZ)",
         "orcid": "0000-0002-5911-1536"},
    ],
    "description": (
        "<p>Grant Agreement: 101082021<br>"
        "Project Acronym: MARCO-BOLO<br>"
        "Project Title: MARine COastal BiOdiversity Long-term Observations<br>"
        "Deliverable Number: D5.4<br>"
        "Work Package Number: WP5<br>"
        "Deliverable Title: Summary of results on the multi-disciplinary mapping of the "
        "alien species distribution and impacts on the European coastal and marine habitats<br>"
        "Due Date: 30.05.2024<br>"
        "Date of delivery (cover): 30.05.2024<br>"
        "Submission (Ares ref): 25.06.2024</p>"

        "<p>This deliverable summarizes the scientific outputs generated by "
        "<strong>Task T5.4</strong> &mdash; &ldquo;Mapping the impacts of Non-Indigenous "
        "species (NIS) on European coastal and marine habitats, based on multi-disciplinary "
        "approaches&rdquo;. In this task we integrated species occurrence data with "
        "environmental information to produce invasive heat maps and alien forecasts for the "
        "European coastline. These were then verified by alien species observations from the "
        "genetic observatory network EMO BON.</p>"

        "<p>Overall, we used a selection of 35 known marine alien species to predict suitable "
        "habitat for individual species as well as to identify potential invasive hotspots. "
        "Most of the individual models detected areas with suitable habitat where the species "
        "have not yet been reported from. The hotspot models identified regions with elevated "
        "risk for establishment and spread of alien species. These were located in the "
        "Southern North Sea, the northern Bay of Biscay, the Northern Adriatic Sea, the "
        "Northern Skagerrak, the Bay of Gdansk, and the eastern Black Sea.</p>"

        "<p>We could match observations of 32 alien species detected by the genetic "
        "observatories network ARMS-MBON against the predicted hotspots and found a "
        "reasonable overlap between the model predictions and the observations of alien "
        "species made by the genetic observatories. We conclude that ARMS-MBON and EMO BON "
        "may be used in the future to forecast, detect, and monitor the spread of alien "
        "species on a continental scale.</p>"
    ),
    "keywords": [
        "MBO WP5", "alien species", "species distribution modelling",
        "non-indigenous species", "ARMS-MBON",
    ],
    "communities": [{"identifier": "marco-bolo"}],
    "grants": [{"id": "10.13039/501100000780::101082021"}],
    "related_identifiers": [],
    "dates": [
        {"start": "2024-05-30", "type": "Created",
         "description": "Date on cover"},
        {"start": "2024-06-25", "type": "Submitted",
         "description": "Submission date (Ares ref)"},
        {"start": "2024-05-30", "type": "Other",
         "description": "Due date"},
    ],
}

# ---------------------------------------------------------------------------
# HTTP plumbing
# ---------------------------------------------------------------------------
def make_ssl_context():
    try:
        import certifi
        return ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        return ssl.create_default_context()

def load_token():
    tok = os.environ.get("ZENODO_TOKEN")
    if tok: return tok.strip()
    tok_file = Path.home() / ".zenodo_token"
    if tok_file.exists():
        return tok_file.read_text().strip()
    print("ERROR: no Zenodo token.", file=sys.stderr); sys.exit(1)

def request(method, url, token, ctx, json_body=None, raw_body=None,
            content_type=None):
    headers = {"Authorization": f"Bearer {token}"}
    if json_body is not None:
        data = json.dumps(json_body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    elif raw_body is not None:
        data = raw_body
        if content_type: headers["Content-Type"] = content_type
    else:
        data = None
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=120, context=ctx) as r:
            body = r.read().decode("utf-8") if r.length != 0 else ""
            return r.status, json.loads(body) if body else {}
    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8", errors="replace")
        print(f"\nHTTP {e.code} {e.reason} on {method} {url}", file=sys.stderr)
        print(f"Response body:\n{err_body}", file=sys.stderr)
        sys.exit(2)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pdf", required=True)
    ap.add_argument("--draft", action="store_true")
    ap.add_argument("--yes", action="store_true")
    args = ap.parse_args()

    pdf = Path(args.pdf).expanduser().resolve()
    if not pdf.is_file():
        print(f"ERROR: file not found: {pdf}", file=sys.stderr); sys.exit(1)

    token = load_token()
    ctx = make_ssl_context()
    base = "https://zenodo.org"
    print(f"Target: LIVE ({base})")
    print(f"File:   {pdf}  ({pdf.stat().st_size:,} bytes)")
    print(f"Title:  {METADATA['title'][:80]}...")
    print(f"Authors: {len(METADATA['creators'])}\n")

    print("Step 1/4: creating draft deposit ...")
    status, dep = request("POST", f"{base}/api/deposit/depositions", token, ctx,
                          json_body={})
    deposit_id = dep["id"]
    bucket_url = dep["links"]["bucket"]
    html_url = dep["links"].get("html") or f"{base}/deposit/{deposit_id}"
    print(f"  deposit id: {deposit_id}\n  review URL: {html_url}")

    print(f"\nStep 2/4: uploading {pdf.name} ...")
    with open(pdf, "rb") as fh: body = fh.read()
    status, fileinfo = request("PUT", f"{bucket_url}/{pdf.name}", token, ctx,
                               raw_body=body,
                               content_type="application/octet-stream")
    print(f"  uploaded ({fileinfo.get('size','?')} bytes)")

    print("\nStep 3/4: setting metadata ...")
    status, dep = request("PUT", f"{base}/api/deposit/depositions/{deposit_id}",
                          token, ctx, json_body={"metadata": METADATA})
    print(f"  metadata saved. Reserved DOI: "
          f"{dep['metadata'].get('prereserve_doi',{}).get('doi','(unknown)')}")

    if args.draft:
        print(f"\nStep 4/4: SKIPPED (--draft). Review/publish at:\n  {html_url}")
        return
    if not args.yes:
        print(f"\nReview the draft here before publishing:\n  {html_url}")
        ans = input("\nPublish now to LIVE? Permanent DOI. [y/N]: ")
        if ans.strip().lower() not in ("y", "yes"):
            print(f"Not publishing. Draft saved at:\n  {html_url}")
            return

    print("\nStep 4/4: publishing ...")
    status, dep = request(
        "POST", f"{base}/api/deposit/depositions/{deposit_id}/actions/publish",
        token, ctx)
    final_doi = dep.get("doi") or dep["metadata"].get("doi")
    final_url = dep["links"].get("record_html") or dep["links"].get("html")
    print("\n✓ Published.")
    print(f"  DOI:    {final_doi}")
    print(f"  URL:    {final_url}")

if __name__ == "__main__":
    main()
